name: Run code quality checks

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

permissions:
    contents: read

jobs:
    run_code_quality_checks:
        strategy:
            matrix:
                php:
                    - 8.3
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: pdo_sqlite
            -   run: composer install --no-progress
            -   run: composer code-quality
